name: camiimac
favicon: null
layout_spectrum: 0.1083222075831145
typography_spectrum: 0.482563987839967
title: 'designer, speaker, good juju spreader, strategist, author, listener'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#586e96'
    - '#7fc192'
    - '#ce4d30'
    - '#85902a'
  brandStrength: 0.8345343873370439
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
