name: camiimac
favicon: null
layout_spectrum: 0.1083222075831145
typography_spectrum: 0.482563987839967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8345343873370439
  lightness: 0.5686840552370995
  saturation: 0.7188480964396149
  rhythmicContrast: 0.5502509844955057
purpose: []
